<?php
return [
	/*
  	*   Set values for interacting with the CREST API
  	*/
	'client_id' => 'your_client_id_here',
	'secret_key' => 'your_secret_key_here',
	'callback_url' => 'https://your-application.com/callback',
	'authorize' => false,
	'user_agent' => 'CRESTer',
	'check_state' => false,
	'limiter' => [
		'limit' => 60,
		'frequency' =>	60,
	],
	'xmlAPI' =>[
		'CrestAuth' => false
	],
	'scopes' => [
		"characterContactsRead", 
		"characterContactsWrite", 
		"characterFittingsRead", 
		"characterFittingsWrite", 
		"characterLocationRead", 
		"characterNavigationWrite", 
		"publicData", 
		"fleetRead", 
		"fleetWrite", 
		/*"characterSkillsRead", 
		"corporationBookmarksRead", 
		"structureVulnUpdate", 
		"characterAccountRead", 
		"characterAssetsRead", 
		"characterBookmarksRead", 
		"characterCalendarRead", 
		"characterChatChannelsRead", 
		"characterClonesRead", 
		"characterContactsRead", 
		"characterFactionalWarfareRead", 
		"characterIndustryJobsRead", 
		"characterKillsRead", 
		"characterLoyaltyPointsRead", 
		"characterMailRead", 
		"characterMarketOrdersRead", 
		"characterMedalsRead", 
		"characterNotificationsRead", 
		"characterOpportunitiesRead", 
		"characterResearchRead", 
		"characterWalletRead", 
		"corporationAssetRead", 
		"corporationBookmarksRead", 
		"corporationContractsRead", 
		"corporationFactionalWarfareRead", 
		"corporationIndustryJobsRead", 
		"corporationKillsRead", 
		"corporationMarketOrdersRead", 
		"corporationMedalsRead", 
		"corporationMembersRead", 
		"corporationShareholdersRead", 
		"corporationStructuresRead", 
		"corporationWalletRead",
		"characterStatsRead",*/
	],
];